# Generated by Django 4.0.2 on 2022-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О компании')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емейл')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона 2')),
                ('phone_number_3', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона 3')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емейл адрес')),
            ],
        ),
        migrations.CreateModel(
            name='ForPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Для партнёров')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Об основателе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='founder_photo')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.TextField(blank=True, null=True, verbose_name='Оплата')),
                ('delivery', models.TextField(blank=True, null=True, verbose_name='Доставка')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на инстаграм')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на фейсбук')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Сссылка на телеграм')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Whatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Положения и условия')),
                ('privacy', models.TextField(blank=True, null=True, verbose_name='Политика конфеденциальности')),
                ('copyright', models.TextField(blank=True, null=True, verbose_name='Политика авторского права')),
            ],
        ),
    ]
