# Generated by Django 4.0.2 on 2022-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_contactformstatus_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Инструкция для продавцов')),
            ],
            options={
                'verbose_name': 'Продай уже сейчас',
                'verbose_name_plural': 'Продай уже сейчас',
            },
        ),
    ]
