# Generated by Django 4.0.2 on 2022-03-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_region_options_remove_author_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона заказчика')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за единицу')),
                ('total_sum', models.PositiveIntegerField(blank=True, null=True, verbose_name=' Общая сумма')),
                ('order_status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.painting', verbose_name='Заказанная картина')),
            ],
            options={
                'verbose_name': 'Заказ картины',
                'verbose_name_plural': 'Заказ картин',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HandicraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона заказчика')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за единицу')),
                ('total_sum', models.PositiveIntegerField(blank=True, null=True, verbose_name=' Общая сумма')),
                ('order_status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.handicraft', verbose_name='Заказанное ремесленное изделие')),
            ],
            options={
                'verbose_name': 'Заказ ремесленного изделия',
                'verbose_name_plural': 'Заказ ремесленных изделий',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CeramicOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Номер телефона заказчика')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за единицу')),
                ('total_sum', models.PositiveIntegerField(blank=True, null=True, verbose_name=' Общая сумма')),
                ('order_status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ceramic', verbose_name='Заказанное керамическое изделие')),
            ],
            options={
                'verbose_name': 'Заказ керамического изделия',
                'verbose_name_plural': 'Заказ керамических изделий',
                'ordering': ['-created'],
            },
        ),
    ]
