# Generated by Django 4.0.2 on 2022-03-09 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('country', models.CharField(max_length=250, verbose_name='Страна доставки')),
                ('region', models.CharField(max_length=250, verbose_name='Область')),
                ('city', models.CharField(max_length=250, verbose_name='Город/Населенный пункт')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарии к заказу')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('total_price', models.FloatField(verbose_name='Итоговая стоимость заказа')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за единицу')),
                ('products_id', models.PositiveIntegerField(verbose_name='Артикул товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Заказ модел',
                'verbose_name_plural': 'Заказы модели',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='handicraftorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paintingorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='CeramicOrder',
        ),
        migrations.DeleteModel(
            name='HandicraftOrder',
        ),
        migrations.DeleteModel(
            name='PaintingOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus', verbose_name='Статус Заказа'),
        ),
    ]
