# Generated by Django 4.0.2 on 2022-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderstatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Категория товара'),
        ),
    ]
