# Generated by Django 4.0.2 on 2022-02-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И. автора')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Об авторе')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CeramicMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал изделия')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CeramicTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Техника создания')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техники',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CeramicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HandicraftMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал изделия')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HandicraftTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Техника создания')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техники',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HandicraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделий',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='PaintMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал живописи')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PaintTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Техника живописи')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техники',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стиль живописи')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема картины')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название картины')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (см)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (см)')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.author', verbose_name='Автор')),
                ('color', models.ManyToManyField(blank=True, to='products.Color', verbose_name='Цвет')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.paintmaterial', verbose_name='Материал')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.style', verbose_name='Стиль')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subject', verbose_name='Тема')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.painttechnique', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Handicraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название изделия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='handicrafts_images', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.author', verbose_name='Автор')),
                ('color', models.ManyToManyField(blank=True, to='products.Color', verbose_name='Цвет')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.handicraftmaterial', verbose_name='Материал')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.handicrafttechnique', verbose_name='Техника')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.handicrafttype', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Ремесленное изделие',
                'verbose_name_plural': 'Ремесленные изделия',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ceramic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название изделия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ceramics_images', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.author', verbose_name='Автор')),
                ('color', models.ManyToManyField(blank=True, to='products.Color', verbose_name='Цвет')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ceramicmaterial', verbose_name='Материал')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ceramictechnique', verbose_name='Техника')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ceramictype', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Керамика',
                'verbose_name_plural': 'Керамика',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.origin', verbose_name='Регион'),
        ),
    ]
