# Generated by Django 4.0.2 on 2022-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_country_region_alter_origin_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область'),
        ),
    ]
