# Generated by Django 4.0.2 on 2022-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_region_options_remove_author_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ф.И. автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='ceramics_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название изделия'),
        ),
        migrations.AlterField(
            model_name='ceramicmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Материал керамического изделия'),
        ),
        migrations.AlterField(
            model_name='ceramictechnique',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Техника создания'),
        ),
        migrations.AlterField(
            model_name='ceramictype',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Тип керамики'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='handicrafts_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название изделия'),
        ),
        migrations.AlterField(
            model_name='handicraftmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Материал ремесленного изделия'),
        ),
        migrations.AlterField(
            model_name='handicrafttechnique',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Техника создания'),
        ),
        migrations.AlterField(
            model_name='handicrafttype',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Тип ремесленного изделия'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='paintings_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название картины'),
        ),
        migrations.AlterField(
            model_name='paintmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Материал живописи'),
        ),
        migrations.AlterField(
            model_name='painttechnique',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Техника живописи'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Стиль живописи'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Тема картины'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('title', 'country')},
        ),
    ]
