# Generated by Django 4.0.2 on 2022-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_author_about_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область'),
        ),
    ]
