# Generated by Django 4.0.2 on 2022-03-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_region_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Область'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'phone_number', 'about', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='ceramic',
            unique_together={('title', 'photo', 'description', 'type', 'material', 'technique', 'author', 'price', 'keywords')},
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('title', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='handicraft',
            unique_together={('title', 'photo', 'description', 'type', 'material', 'technique', 'author', 'price', 'keywords')},
        ),
        migrations.AlterUniqueTogether(
            name='painting',
            unique_together={('title', 'photo', 'description', 'subject', 'material', 'style', 'technique', 'width', 'height', 'author', 'price', 'keywords')},
        ),
    ]
