# Generated by Django 4.0.2 on 2022-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_author_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='painting',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='painting',
            name='recommended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Рекомендованный'),
        ),
    ]
