# Generated by Django 4.0.2 on 2022-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_ceramic_created_at_ceramic_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ceramic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='handicraft',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='painting',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И. автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ceramics_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ceramic',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название изделия'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='handicrafts_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='handicraft',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название изделия'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название картины'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'phone_number', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='ceramic',
            unique_together={('title', 'description', 'type', 'material', 'technique', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='handicraft',
            unique_together={('title', 'type', 'material', 'technique', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='painting',
            unique_together={('title', 'subject', 'material', 'style', 'technique', 'width', 'height', 'author')},
        ),
    ]
