# Generated by Django 4.0.2 on 2022-03-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_author_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
