# Generated by Django 4.0.2 on 2022-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_author_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceramic',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='handicraft',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='photo',
        ),
        migrations.AddField(
            model_name='ceramic',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 1'),
        ),
        migrations.AddField(
            model_name='ceramic',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 2'),
        ),
        migrations.AddField(
            model_name='ceramic',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 3'),
        ),
        migrations.AddField(
            model_name='ceramic',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 4'),
        ),
        migrations.AddField(
            model_name='ceramic',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 5'),
        ),
        migrations.AddField(
            model_name='handicraft',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 1'),
        ),
        migrations.AddField(
            model_name='handicraft',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 2'),
        ),
        migrations.AddField(
            model_name='handicraft',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 3'),
        ),
        migrations.AddField(
            model_name='handicraft',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 4'),
        ),
        migrations.AddField(
            model_name='handicraft',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 5'),
        ),
        migrations.AddField(
            model_name='painting',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 1'),
        ),
        migrations.AddField(
            model_name='painting',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 2'),
        ),
        migrations.AddField(
            model_name='painting',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 3'),
        ),
        migrations.AddField(
            model_name='painting',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 4'),
        ),
        migrations.AddField(
            model_name='painting',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='paintings_images', verbose_name='Фото - 5'),
        ),
    ]
