# Generated by Django 4.0.2 on 2022-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_ceramic_photo_remove_handicraft_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='featured',
            field=models.BooleanField(blank=True, null=True, verbose_name='показанный'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author photo', verbose_name='фото мастера'),
        ),
    ]
